services:
  - type: web
    name: wind-forecast-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ELEXON_BASE_URL
        value: https://data.elexon.co.uk/bmrs/api/v1
    rootDir: backend/
